---
# tasks file for logstash-role

- include: logstash_requirements.yml

- include: logstash_installation_Debian.yml
  when: ansible_os_family == "Debian"

- include: logstash_installation_RedHat.yml
  when: ansible_os_family == "RedHat"

- include: logstash_plugins.yml

- include: logstash_configuration.yml
